version: '3.8'

services:
  app:
    build:
      context: .
    image: send_new_earthquake_app
    ports:
      - "12000:12000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
